-- welcome screen displaying all tags available to search
local nm = require("notmuch")
local r = require("notmuch.refresh")
local s = require("notmuch.sync")

vim.keymap.set("n", "<CR>", function()
  nm.open_hello_line()
end, { buffer = true })
vim.keymap.set("n", "c", function()
  nm.count_hello_line()
end, { buffer = true })
vim.keymap.set("n", "q", "<Cmd>bwipeout<CR>", { buffer = true })
vim.keymap.set("n", "r", r.refresh_hello_buffer, { buffer = true })
vim.keymap.set("n", "C", require("notmuch.send").compose, { buffer = true })
vim.keymap.set("n", "D", require("notmuch.send").select_draft, { buffer = true })
vim.keymap.set("n", "%", s.sync_maildir, { buffer = true })
